version: '3.7'
services:
  web:
    container_name: web-container
    build: ./docker/web
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:cached # (1)
    tty: true
    depends_on:
      - db
  db:
    container_name: db-container
    image: postgres:12.1-alpine
    volumes:
      - ./docker/db/storage:/var/lib/postgresql/data:cached # (2)
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8' # (3)
      TZ: Asia/Tokyo # (3)
